routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\JurusanController;
use App\Http\Controllers\SiswaController;
use App\Http\Controllers\ExampleController;
use App\Http\Controllers\KelasController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Auth::routes();

Route::get('/', [ExampleController::class , 'index']);
Route::group(['middleware' => 'auth', 'prefix' => 'admin' , 'as' => 'admin.'], function(){
    Route::get('/', [ExampleController::class, 'admin'])->name('admin');

    Route::get('/kelas', [KelasController::class, 'index'])->name('kelas');
    Route::get('/create', [KelasController::class, 'create'])->name('create');
    Route::post('/create', [KelasController::class, 'store'])->name('store');

    Route::get('/update/{kelas:id}', [KelasController::class, 'edit'])->name('edit');
    Route::put('/update/{id}', [KelasController::class, 'update'])->name('update');
    
    Route::delete('/delete/{id}', [KelasController::class, 'destroy'])->name('destroy');
    
    Route::group(['prefix' => 'siswa', 'as' => 'siswa.'], function(){
        Route::get('/', [SiswaController::class, 'index'])->name('index');
        Route::get('/create', [SiswaController::class, 'create'])->name('create');
        Route::post('/', [SiswaController::class, 'store'])->name('store');
        Route::get('/{siswa}', [SiswaController::class, 'edit'])->name('edit');
        Route::put('/{siswa}', [SiswaController::class, 'update'])->name('update');
        Route::delete('/{siswa}', [SiswaController::class, 'destroy'])->name('delete');
    });
    Route::group(['prefix' => 'jurusan', 'as' => 'jurusan.'], function(){
        Route::get('/', [JurusanController::class, 'jurusan'])->name('jurusan');
        Route::post('/simpanjurusan', [JurusanController::class, 'simpan'])->name('simpanJurusan');
        Route::post('/hapusjurusan/{id}', [JurusanController::class, 'hapus'])->name('hapusJurusan');
        Route::get('/editjurusan/{jurusan:id}', [JurusanController::class, 'edit'])->name('editJurusan');
        Route::get('/tambahjurusan', [JurusanController::class, 'tambah'])->name('tambahJurusan');
        Route::post('/ubahjurusan/{id}', [JurusanController::class, 'ubah'])->name('ubahJurusan');
    });

    Route::get('/kelas/create', [KelasController::class, 'create'])->name('create');
});

Route::get('/debug', [SiswaController::class, 'index']);

app/Models/Jurusan.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Jurusan extends Model
{

    use HasFactory;
    protected $guarded = [];

    public function kelas() {
        return $this->hasMany(Kelas::class);
    }
}

app/Http/Controllers/JurusanController.php
<?php

namespace App\Http\Controllers;

use App\Models\Jurusan;
use Illuminate\Http\Request;

class JurusanController extends Controller
{
    public function jurusan() {
        $jurusan = Jurusan::all();
        return view('jurusan.jurusan', compact('jurusan'));
    }
    public function simpan(Request $request) {
       Jurusan::create([
        "nama_jurusan" => $request->nama_jurusan
       ]);

       return redirect()->route('admin.jurusan.jurusan');
    }
    public function edit(Jurusan $jurusan) {
        $data = $jurusan;
        return view('jurusan.action', compact('data'));
    }
    public function hapus($id){

        $jurusan = Jurusan::find($id);
        $jurusan->delete();
        return redirect()->route('admin.jurusan.jurusan');
    }
    public function ubah(Request $request , $id){

        $jurusan = Jurusan::find($id);
        $jurusan->update(["nama_jurusan" => $request->nama_jurusan]);
        return redirect()->route('admin.jurusan.jurusan');
    }
    public function tambah(){
        $data = null;
        return view('jurusan.action',compact('data'));
    }

}

resources/views/jurusan/action.blade.php
@extends('layouts.app')
@section('content')
    <div class="card">
        <div class="card-body">
        @if ($data)
            <form action="{{ route('admin.jurusan.ubahJurusan', $data->id) }}" method="post">
        @endif
        <form action="{{ route('admin.jurusan.simpanJurusan') }}" method="post">
            @csrf
            <input type="text" name="nama_jurusan" class="form-control" value="{{ $data ? $data->nama_jurusan : " " }}">
            <button type="submit" class="btn btn-primary mt-2     ">Simpan</button>
        </form>  
    </div>
</div>
@endsection

resources/views/jurusan/jurusan.blade.php
@extends('layouts.app')
@section('content')
    <div class="card">
        <div class="card-body">
            <a href="{{ route('admin.jurusan.tambahJurusan') }}" class="btn btn-primary">Tambah</a>
            <table class="table" style="margin-top: 20px;">
                <thead>
                    <tr>
                      <th scope="col">Id</th>
                      <th scope="col">Nama Jurusan</th>
                      <th scope="col">Section</th>
                    </tr>
                  </thead>
                  <tbody>
                      @foreach ($jurusan as $key => $item)
                    <form action="{{ route('admin.jurusan.hapusJurusan', $item->id) }}" method="post">
                        @csrf
                      <tr>
                        <td>{{ $key+1 }}</td>
                        <td>{{ $item->nama_jurusan }}</td>
                        <td>
                            <a href="{{ route('admin.jurusan.editJurusan', $item->id) }}" class="btn btn-warning">Edit</a>
                            <button class="btn btn-danger" type="submit">Hapus</button>
                        </td>
                      </tr>
                    </form>
                      @endforeach
                </tbody>
            </table>
        </div>
    </div>
</div>
@endsection