routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\JurusanController;
use App\Http\Controllers\SiswaController;
use App\Http\Controllers\ExampleController;
use App\Http\Controllers\KelasController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Auth::routes();

Route::get('/', [ExampleController::class , 'index']);
Route::group(['middleware' => 'auth', 'prefix' => 'admin' , 'as' => 'admin.'], function(){
    Route::get('/', [ExampleController::class, 'admin'])->name('admin');

    Route::get('/kelas', [KelasController::class, 'index'])->name('kelas');
    Route::get('/create', [KelasController::class, 'create'])->name('create');
    Route::post('/create', [KelasController::class, 'store'])->name('store');

    Route::get('/update/{kelas:id}', [KelasController::class, 'edit'])->name('edit');
    Route::put('/update/{id}', [KelasController::class, 'update'])->name('update');
    
    Route::delete('/delete/{id}', [KelasController::class, 'destroy'])->name('destroy');
    
    Route::group(['prefix' => 'siswa', 'as' => 'siswa.'], function(){
        Route::get('/', [SiswaController::class, 'index'])->name('index');
        Route::get('/create', [SiswaController::class, 'create'])->name('create');
        Route::post('/', [SiswaController::class, 'store'])->name('store');
        Route::get('/{siswa}', [SiswaController::class, 'edit'])->name('edit');
        Route::put('/{siswa}', [SiswaController::class, 'update'])->name('update');
        Route::delete('/{siswa}', [SiswaController::class, 'destroy'])->name('delete');
    });
    Route::group(['prefix' => 'jurusan', 'as' => 'jurusan.'], function(){
        Route::get('/', [JurusanController::class, 'jurusan'])->name('jurusan');
        Route::post('/simpanjurusan', [JurusanController::class, 'simpan'])->name('simpanJurusan');
        Route::post('/hapusjurusan/{id}', [JurusanController::class, 'hapus'])->name('hapusJurusan');
        Route::get('/editjurusan/{jurusan:id}', [JurusanController::class, 'edit'])->name('editJurusan');
        Route::get('/tambahjurusan', [JurusanController::class, 'tambah'])->name('tambahJurusan');
        Route::post('/ubahjurusan/{id}', [JurusanController::class, 'ubah'])->name('ubahJurusan');
    });

    Route::get('/kelas/create', [KelasController::class, 'create'])->name('create');
});

Route::get('/debug', [SiswaController::class, 'index']);

app/Models/Kelas.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Kelas extends Model
{
    use HasFactory;
    protected $guarded = [];

    public function jurusan() {
        return $this->belongsTo(Jurusan::class);
    }
}

app/Http/Controllers/KelasController.php
<?php

namespace App\Http\Controllers;

use App\Models\Jurusan;
use App\Models\Kelas;
use Illuminate\Http\Request;

class KelasController extends Controller
{
    public function index() {
        return view('pages.kelas.index', [
            "kelas" => Kelas::all()
        ]);
    }
    
    public function create(){
        $data = null;

        return view('pages.kelas.action', [
            "data" => $data,
            "jurusan" => Jurusan::all()
        ]);
    }

    public function store(Request $request) {
        $validatedData = $request->validate([
            'name' => 'required|max:255',
            'jurusan_id' => 'required'
        ]);

        Kelas::create($validatedData);

        return redirect()->route('admin.admin')->with('success', 'Data kelas berhasil ditambahkan');
    }

    public function edit(Kelas $kelas) {
        $data = $kelas;
        
        return view('pages.kelas.action', [
            "data" => $data,
            "jurusan" => Jurusan::all()
        ]);
    }

    public function update(Request $request) {
        $validatedData = $request->validate([
            'name' => 'required|min:3',
            'jurusan_id' => 'required'
        ]);

        Kelas::where('id', $request->id)->update([
            'name' => $validatedData['name'],
            'jurusan_id' => $validatedData['jurusan_id']
        ]);
        
        return redirect()->route('admin.admin')->with('success', 'Data kelas berhasil diubah');
    }

    public function destroy(Request $request) {
        Kelas::destroy($request->id);
        
        return redirect()->route('admin.admin')->with('success', 'Data kelas berhasil dihapus');
    }
}

resources/views/pages/kelas/action.blade.php
@extends('layouts.app')
@section('content')
    <link rel="stylesheet" href="/backend/app-assets/css/uploader.css">
    <link rel="stylesheet" href="/backend/app-assets/css/uploader-2.css">

    <div class="content-header row">
        <div class="content-header-left col-md-9 col-12 mb-2">
            <div class="row breadcrumbs-top">
                <div class="col-12">
                    <div class="breadcrumb-wrapper">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a href="#">Home</a>
                            </li>
                            <li class="breadcrumb-item"><a href="#">Your Page</a>
                            </li>
                            <li class="breadcrumb-item active">
                                @if ($data == null)
                                Create Your Page
                                @else
                                Update Your Page
                                @endif
                            </li>
                        </ol>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="content-body">
    <!-- Validation -->
        <section class="bs-validation">
            @if ($data !== null)
                <form action="{{ route('admin.update', $data->id) }}" id="jquery-val-form" method="POST" enctype="multipart/form-data"> <!-- jika form edit -->
                    @method('PUT')
            @else
                <form action="{{ route('admin.store') }}" method="POST" enctype="multipart/form-data"> <!-- jika form tambah -->
            @endif
                @csrf
                <div class="row">
                    <!-- Bootstrap Validation -->
                    <div class="col-md-12 col-12">
                        <div class="card">
                            <div class="card-header">
                                <h4 class="card-title">
                                    @if ($data == null)
                                        Tambah data kelas
                                    @else
                                        Update data kelas
                                    @endif
                                </h4>
                            </div>
                            <div class="card-body">
                                <div class="form-group">
                                    <label for="name">Name</label>
                                    <input type="text" name="name" id="name" class="form-control @error('name') border-danger @enderror" value="{{ $data ? $data->name : '' }}">
                                    @error('name')
                                        <span class="text-danger">{{ $message }}</span>
                                    @enderror
                                </div>
                                <div class="form-group">
                                    <label for="jurusan" class="form-label">Jurusan</label>
                                    <select class="form-select form-control" name="jurusan_id" id="jurusan_id" value="{{ old('jurusan_id') }}">
                                        @foreach ($jurusan as $jur)
                                            @if ($data && $data->jurusan_id == $jur->id)
                                                <option value="{{ $jur->id }}" selected>{{ $jur->nama_jurusan }}</option>
                                            @else
                                                @if (old('jurusan_id') == $jur->id)
                                                    <option value="{{ $jur->id }}" selected>{{ $jur->nama_jurusan }}</option>
                                                @else
                                                    <option value="{{ $jur->id }}">{{ $jur->nama_jurusan }}</option>
                                                @endif
                                            @endif
                                        @endforeach
                                    </select>
                                </div>
                                
                            </div>
                        </div>
                    </div>
                </div>

                <div class="row mb-4">
                    <div class="col-md-6">
                        <button type="submit"
                        data-initial-text="Update <i class='icon-paperplane ml-2'></i>"
                        data-loading-text="<i class='fas fa-spinner fa-spin'></i> Loading..."
                        class="btn btn-primary"> Save Changes </button>
                    </div>
                </div>
            </form>
        </section>
    </div>

@endsection

@section('script')
    <script src="https://cdn.ckeditor.com/4.14.0/standard/ckeditor.js"></script>
    <script>
        $(function(){
            var textarea1 = document.getElementById('description');
            CKEDITOR.replace(textarea1);
        })
    </script>
    <script>

        function readURL2(input) {
            if (input.files && input.files[0]) {

                var reader = new FileReader();

                reader.onload = function(e) {
                $('.image-upload-wrap-2').hide();

                $('.file-upload-image-2').attr('src', e.target.result);
                $('.file-upload-content-2').show();

                $('.image-title-2').html(input.files[0].name);
                };

                reader.readAsDataURL(input.files[0]);

            } else {
                removeUpload2();
            }
        }

        function removeUpload2() {
            $('.file-upload-input-2').replaceWith($('.file-upload-input-2').clone());
            $('.file-upload-content-2').hide();
            $('.image-upload-wrap-2').show();
        }

        $(function (){
            $('.image-upload-wrap-2').bind('dragover', function () {
                $('.image-upload-wrap-2').addClass('image-dropping-2');
            });

            $('.image-upload-wrap-2').bind('dragleave', function () {
                    $('.image-upload-wrap-2').removeClass('image-dropping-2');
            });
        });
    </script>
    @if(Session::get('create'))
        <script type="text/javascript">
            $(document).ready(function(){

             // Success Type
                toastr['success']('Successfully Create Data.', 'Successfully', {
                    closeButton: true,
                    tapToDismiss: false,
                    progressBar: true,
                });

            });
        </script>
    @endif

    @if(Session::get('update'))
    <script type="text/javascript">
        $(document).ready(function(){

            // Success Type
            toastr['success']('Successfully Update Data.', 'Successfully', {
                closeButton: true,
                tapToDismiss: false,
                progressBar: true,
            });

        });
    </script>
    @endif

@endsection

resources/views/pages/kelas/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="content-header row">
        <div class="content-header-left col-md-9 col-12 mb-2">
            <div class="row breadcrumbs-top">
                <div class="col-12">
                    <div class="breadcrumb-wrapper">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a href="#">Home</a>
                            </li>
                            <li class="breadcrumb-item"><a href="#">Siswa</a>
                            </li>
                        </ol>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="content-body">
        @if (session()->has('success'))
            <div class="alert alert-success" role="alert">
                {{ session('success') }}
            </div>
        @endif
        <!-- Basic table -->
        <section id="ajax-datatable">
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-header border-bottom">
                            <h4 class="card-title">Kelas List</h4>
                            <div>
                                <a href="{{ route('admin.create') }}" class="btn btn-primary">Add Data</a>
                            </div>
                        </div>
                        <div class="card-datatable">
                            <table class="table" id="data-notif">
                                <thead>
                                    <tr>
                                        <th>No</th>
                                        <th>Name</th>
                                        <th>Jurusan</th>
                                        <th>Action</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach ($kelas as $item)
                                        <tr>
                                            <td>{{ $loop->iteration }}</td>
                                            <td>{{ $item->name }}</td>
                                            <td>{{ $item->jurusan->nama_jurusan }}</td>
                                            <td class="d-flex">
                                                <a href="{{ route('admin.edit', $item->id) }}" class="btn btn-primary mr-1">Update</a>
                                                <form action="{{ route('admin.destroy', $item->id) }}" method="POST">
                                                    @method('delete')
                                                    @csrf
                                                    <button type="submit" class="btn btn-danger">Update</button>
                                                </form>
                                            </td>
                                        </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <!--/ Basic table -->
    </div>

    @endsection

    @section('script')
    {{-- Jika anda mau menggunakan data tables sialahkan un command script ini --}}
    {{-- <script>
        $(function(){
            $.ajaxSetup({
                headers: {
                    'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                }
            });

            var table = $('#data-notif').DataTable({
                processing: true,
                serverSide: true,
                ajax: "url yang akan di tuju",
                columns: [
                {
                    data: null, "sortable": false,
                    render: function (data, type, row, meta) { return meta.row + meta.settings._iDisplayStart + 1; },
                },
                {
                    data: 'Column',
                    render: function (data, type, row, meta) {
                        return ``
                    },
                },
                {
                    data: 'id',
                    render: function (data, type, row, meta) {
                        return `
                            <div class="btn-group">
                                <button class="btn btn-flat-dark dropdown-toggle" type="button" id="dropdownMenuButton100" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    <img src="/app-assets/images/align-justify.svg">
                                </button>
                                <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                                    <a class="dropdown-item" href="/admin/eskul/edit/${row.id}">Edit</a>
                                    <a class="dropdown-item" href="javascript:void(0);" onclick="return hapus(${row.id})">Hapus</a>
                                </div>
                            </div>`
                    }
                },
                ],
                columnDefs: [
                {
                    className: 'control',
                    orderable: false,
                    targets: 0
                }
                ],
                dom:
                '<"d-flex justify-content-between align-items-center mx-0 row"<"col-sm-12 col-md-6"l><"col-sm-12 col-md-6"f>>t<"d-flex justify-content-between mx-0 row"<"col-sm-12 col-md-6"i><"col-sm-12 col-md-6"p>>',
                orderCellsTop: true,
                responsive: {
                    details: {
                        display: $.fn.dataTable.Responsive.display.modal({
                            header: function (row) {
                                var data = row.data();
                                return 'Details of ' + data['full_name'];
                            }
                        }),
                        type: 'column',
                        renderer: $.fn.dataTable.Responsive.renderer.tableAll({
                            tableClass: 'table'
                        })
                    }
                },
                language: {
                    paginate: {
                        // remove previous & next text from pagination
                        previous: '&nbsp;',
                        next: '&nbsp;'
                    }
                },
                drawCallback: () => {
                    $('.delete').click(function () {
                        const id = $(this).data(id)
                    })
                }
            });
        });

        function hapus(id){
            var table = $('#data-notif').DataTable();
            clearToastObj = toastr['error'](
                'Are You Delete?<br /><br /><button type="button" class="btn btn-danger btn-sm delete">Yes</button>',
                'Deleted',
                {
                    closeButton: true,
                    timeOut: 0,
                    extendedTimeOut: 0,
                    tapToDismiss: false,
                }
                );

            if (clearToastObj.find('.delete').length) {
                clearToastObj.delegate('.delete', 'click', function () {
                    toastr.clear(clearToastObj, { force: true });
                    clearToastObj = undefined;
                    $.ajax({
                        method: "GET",
                        url: "/admin/eskul/delete/" + id,
                        success: function (data) {
                            toastr['success']('Successfully Delete Data.', 'Successfully', {
                                closeButton: true,
                                tapToDismiss: false,
                                progressBar: true,
                            });
                            table.ajax.reload();
                        },
                        error: function (data) {
                            toastr['success']('👋 Chocolate oat cake jelly oat cake candy jelly beans pastry.', 'Progress Bar', {
                                closeButton: true,
                                tapToDismiss: false,
                                progressBar: true,
                                rtl: isRtl
                            });
                        }
                    });
                });
            }
        }
    </script>
    <script>
        $(function (){
            $('.hapus').on('click', function () {
                var id = $(this).attr('data-id');
                console.log(id);
            });
        });
    </script>
    <script>
        CKEDITOR.replace( 'editor1' );
    </script>
    @if(Session::get('create'))
        <script type="text/javascript">
            $(document).ready(function(){

                // Success Type
                toastr['success']('Successfully Create Data.', 'Successfully', {
                    closeButton: true,
                    tapToDismiss: false,
                    progressBar: true,
                });

            });
        </script>
    @endif

    @if(Session::get('update'))
        <script type="text/javascript">
            $(document).ready(function(){

                // Success Type
                toastr['success']('Successfully Update Data.', 'Successfully', {
                    closeButton: true,
                    tapToDismiss: false,
                    progressBar: true,
                });

            });
        </script>
    @endif --}}

@endsection