routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\JurusanController;
use App\Http\Controllers\SiswaController;
use App\Http\Controllers\ExampleController;
use App\Http\Controllers\KelasController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Auth::routes();

Route::get('/', [ExampleController::class , 'index']);
Route::group(['middleware' => 'auth', 'prefix' => 'admin' , 'as' => 'admin.'], function(){
    Route::get('/', [ExampleController::class, 'admin'])->name('admin');

    Route::get('/kelas', [KelasController::class, 'index'])->name('kelas');
    Route::get('/create', [KelasController::class, 'create'])->name('create');
    Route::post('/create', [KelasController::class, 'store'])->name('store');

    Route::get('/update/{kelas:id}', [KelasController::class, 'edit'])->name('edit');
    Route::put('/update/{id}', [KelasController::class, 'update'])->name('update');
    
    Route::delete('/delete/{id}', [KelasController::class, 'destroy'])->name('destroy');
    
    Route::group(['prefix' => 'siswa', 'as' => 'siswa.'], function(){
        Route::get('/', [SiswaController::class, 'index'])->name('index');
        Route::get('/create', [SiswaController::class, 'create'])->name('create');
        Route::post('/', [SiswaController::class, 'store'])->name('store');
        Route::get('/{siswa}', [SiswaController::class, 'edit'])->name('edit');
        Route::put('/{siswa}', [SiswaController::class, 'update'])->name('update');
        Route::delete('/{siswa}', [SiswaController::class, 'destroy'])->name('delete');
    });
    Route::group(['prefix' => 'jurusan', 'as' => 'jurusan.'], function(){
        Route::get('/', [JurusanController::class, 'jurusan'])->name('jurusan');
        Route::post('/simpanjurusan', [JurusanController::class, 'simpan'])->name('simpanJurusan');
        Route::post('/hapusjurusan/{id}', [JurusanController::class, 'hapus'])->name('hapusJurusan');
        Route::get('/editjurusan/{jurusan:id}', [JurusanController::class, 'edit'])->name('editJurusan');
        Route::get('/tambahjurusan', [JurusanController::class, 'tambah'])->name('tambahJurusan');
        Route::post('/ubahjurusan/{id}', [JurusanController::class, 'ubah'])->name('ubahJurusan');
    });

    Route::get('/kelas/create', [KelasController::class, 'create'])->name('create');
});

Route::get('/debug', [SiswaController::class, 'index']);

app/Models/Siswa.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Siswa extends Model
{
    use HasFactory;

    protected $guarded = ['id'];

    public function kelas()
    {
        return $this->belongsTo(Kelas::class, "kelas_id");
    }
}

app/Http/Controllers/SiswaController.php
<?php

namespace App\Http\Controllers;

use App\Models\Kelas;
use App\Models\Siswa;
use Illuminate\Http\Request;

class SiswaController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data = Siswa::all();
        return view("pages.dashboard.siswa.index", [
            "data" => $data
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $data = null;
        $kelas = Kelas::all();
        return view("pages.dashboard.siswa.action", [
            "header" => "Tambah Data",
            "data" => $data,
            "kelas" => $kelas
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \App\Http\Requests\StoreSiswaRequest  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        Siswa::create($request->except(['_token']));
        return Redirect(route('admin.siswa.index'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Siswa  $siswa
     * @return \Illuminate\Http\Response
     */
    public function edit(Siswa $siswa)
    {
        $data = $siswa;
        $kelas = Kelas::all();
        return view("pages.dashboard.siswa.action", [
            "header" => "Tambah Data",
            "data" => $data,
            "kelas" => $kelas
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \App\Http\Requests\UpdateSiswaRequest  $request
     * @param  \App\Models\Siswa  $siswa
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Siswa $siswa)
    {
        $siswa->update($request->except(['_token']));
        return Redirect(route('admin.siswa.index'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Siswa  $siswa
     * @return \Illuminate\Http\Response
     */
    public function destroy(Siswa $siswa)
    {
        $siswa->delete();
        return Redirect(route('admin.siswa.index'));
    }
}

resources/views/pages/dashboard/siswa/action.blade.php
@extends('layouts.app')
@section('content')
    <link rel="stylesheet" href="/backend/app-assets/css/uploader.css">
    <link rel="stylesheet" href="/backend/app-assets/css/uploader-2.css">

    <div class="content-header row">
        <div class="content-header-left col-md-9 col-12 mb-2">
            <div class="row breadcrumbs-top">
                <div class="col-12">
                    <div class="breadcrumb-wrapper">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a href="{{ route('admin.admin') }}">Home</a></li>
                            <li class="breadcrumb-item"><a href="{{ route('admin.siswa.index') }}">Siswa</a></li>
                            </li>
                            <li class="breadcrumb-item active">
                                @if ($data == null)
                                Add Data
                                @else
                                Update Data
                                @endif
                            </li>
                        </ol>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="card p-2">
    <!-- Validation -->
            @if ($data !== null)
            <form action="{{ route('admin.siswa.update', $data->id) }}" method="POST"> <!-- jika form edit -->
                @method('PUT')
            @else
            <form action="{{ route('admin.siswa.store') }}" method="POST">  <!-- jika form tambah -->
            @endif
                @csrf
                <div class="form-group">
                    <label for="name">Name</label>
                    <input type="text" class="form-control" value="{{ $data ?  $data->name : "" }}" id="name" placeholder="Enter Name" name="name">
                </div>

                <div class="form-group">
                    <label for="nis">NIS</label>
                    <input type="text" class="form-control" value="{{ $data ? $data->nis : "" }}" id="nis" placeholder="Enter Nomor Induk Siswa" name="nis">
                </div>

                <div class="form-group">
                    <label for="dob">Date of Birth</label>
                    <input type="date" class="form-control" id="dob" value="{{ $data ? $data->dob : "" }}" placeholder="Enter Date of Birth" name="dob">
                </div>

                <div class="form-group">
                    <label for="kelas">Gender</label>
                    <select class="custom-select" name="gender" id="gender">\
                        <option {{ $data ? $data->gender == "1" ? "selected" : "" : "" }} value="1">Laki-Laki</option>
                        <option {{ $data ? $data->gender == "2" ? "selected" : "" : "" }} value="2">Perempuan</option>
                    </select>
                </div>

                <div class="form-group">
                    <label for="kelas">Kelas</label>
                    <select class="custom-select" name="kelas_id" id="kelas">
                        @foreach ($kelas as $item)
                            @if ($data && $data->kelas->id === $item->id )
                                <option value="{{ $item->id }}" selected>{{ $item->name }}</option>
                            @else
                                <option value="{{ $item->id }}">{{ $item->name }}</option>
                            @endif
                        @endforeach
                    </select>
                </div>

                <button type="submit" class="btn btn-primary">Submit</button>
            </form>

        {{-- <section class="bs-validation">
            @if (!$data !== null)
            <form action="" method="POST" enctype="multipart/form-data"> <!-- jika form tambah -->
            @else
            <form action="" id="jquery-val-form" method="POST" enctype="multipart/form-data"> <!-- jika form edit -->
            @endif
                @csrf
                <div class="row">
                    <!-- Bootstrap Validation -->
                    <div class="col-md-12 col-12">
                        <div class="card">
                            <div class="card-header">
                                <h4 class="card-title">
                                    @if ($data == null)
                                    Create Your Page
                                    @else
                                    Update Your Page
                                    @endif
                                </h4>
                            </div>
                            <div class="card-body">
                                <div class="file-upload-2  @error('image') border-danger @enderror">
                                    <button class="file-upload-btn-2" type="button" onclick="$('.file-upload-input-2').trigger( 'click' )">Add Image</button>
                                    <div class="image-upload-wrap-2">
                                        <input class="file-upload-input-2" type='file' onchange="readURL2(this);" accept="image/*" name="image" />
                                        <div class="drag-text-2">
                                            @if ($data !== null)
                                                <img class="file-upload-image-2" src="{{ $data ? $data->image : '' }}" alt="your image" />
                                            @else
                                                <h3>Drag and drop a file or select add image</h3>
                                            @endif
                                        </div>
                                    </div>
                                    <div class="file-upload-content-2">
                                        <img class="file-upload-image-2" src="" alt="your image" />
                                        <div class="image-title-wrap-2">
                                            <button type="button" onclick="removeUpload2()" class="remove-image-2">Remove <span class="image-title">Uploaded Icons</span></button>
                                        </div>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label for="">Input Text</label>
                                    <input type="text" name="name" class="form-control @error('name') border-danger @enderror" value="{{ $data ? $data->name : '' }}">
                                    @error('name')
                                        <span class="text-danger">{{ $message }}</span>
                                    @enderror
                                </div>
                                <div class="form-group">
                                    <label for="">CK EDITOR</label>
                                    <textarea name="description" class="form-control" id="description" rows="10">{{ $data ? $data->description : '' }}</textarea>
                                    @error('description')
                                        <span class="text-danger">{{ $message }}</span>
                                    @enderror
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="row mb-4">
                    <div class="col-md-6">
                        <button type="submit"
                        data-initial-text="Update <i class='icon-paperplane ml-2'></i>"
                        data-loading-text="<i class='fas fa-spinner fa-spin'></i> Loading..."
                        class="btn btn-primary"> Save Changes </button>
                    </div>
                </div>
            </form>
        </section> --}}
    </div>

@endsection

{{-- @section('script')
    <script src="https://cdn.ckeditor.com/4.14.0/standard/ckeditor.js"></script>
    <script>
        $(function(){
            var textarea1 = document.getElementById('description');
            CKEDITOR.replace(textarea1);
        })
    </script>
    <script>

        function readURL2(input) {
            if (input.files && input.files[0]) {

                var reader = new FileReader();

                reader.onload = function(e) {
                $('.image-upload-wrap-2').hide();

                $('.file-upload-image-2').attr('src', e.target.result);
                $('.file-upload-content-2').show();

                $('.image-title-2').html(input.files[0].name);
                };

                reader.readAsDataURL(input.files[0]);

            } else {
                removeUpload2();
            }
        }

        function removeUpload2() {
            $('.file-upload-input-2').replaceWith($('.file-upload-input-2').clone());
            $('.file-upload-content-2').hide();
            $('.image-upload-wrap-2').show();
        }

        $(function (){
            $('.image-upload-wrap-2').bind('dragover', function () {
                $('.image-upload-wrap-2').addClass('image-dropping-2');
            });

            $('.image-upload-wrap-2').bind('dragleave', function () {
                    $('.image-upload-wrap-2').removeClass('image-dropping-2');
            });
        });
    </script>
    @if(Session::get('create'))
        <script type="text/javascript">
            $(document).ready(function(){

             // Success Type
                toastr['success']('Successfully Create Data.', 'Successfully', {
                    closeButton: true,
                    tapToDismiss: false,
                    progressBar: true,
                });

            });
        </script>
    @endif

    @if(Session::get('update'))
    <script type="text/javascript">
        $(document).ready(function(){

            // Success Type
            toastr['success']('Successfully Update Data.', 'Successfully', {
                closeButton: true,
                tapToDismiss: false,
                progressBar: true,
            });

        });
    </script>
    @endif

@endsection --}}

resources/views/pages/dashboard/siswa/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="content-header row">
        <div class="content-header-left col-md-9 col-12 mb-2">
            <div class="row breadcrumbs-top">
                <div class="col-12">
                    <div class="breadcrumb-wrapper">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a href="{{ route('admin.admin') }}">Home</a></li>
                            <li class="breadcrumb-item"><a href="{{ route('admin.siswa.index') }}">Siswa</a></li>
                        </ol>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="content-body">
        <!-- Basic table -->
        <section id="ajax-datatable">
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-header border-bottom">
                            <h4 class="card-title">Siswa List</h4>
                            <div>
                                <a href="{{ route('admin.siswa.create') }}" class="btn btn-primary">Add Data</a>
                                {{-- <button type="button" class="btn btn-success" data-toggle="modal" data-target="#exampleModalCenter">
                                    Import Data
                                </button> --}}
                            </div>
                        </div>
                        <div class="card-datatable">
                            <table class="table" id="data-notif">
                                <thead>
                                    <tr>
                                        <th>No</th>
                                        <th>NIS</th>
                                        <th>Kelas</th>
                                        <th>Nama</th>
                                        <th>DOB</th>
                                        <th>Gender</th>
                                        <th>Action</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach ($data as $item)
                                        <tr>
                                            <td>{{ $loop->iteration }}</td>
                                            <td>{{ $item->nis }}</td>
                                            <td>{{ $item->kelas->name }}</td>
                                            <td>{{ $item->name }}</td>
                                            <td>{{ Carbon\Carbon::parse($item->dob)->format('d M Y') }}</td>
                                            <td>{{ $item->gender == 1 ? "Laki-Laki" : "Perempuan" }}</td>
                                            <td>
                                                <div class="d-flex align-items-center justify-content-center" style="column-gap: 10px">
                                                    <a href="{{ route("admin.siswa.edit", $item->id) }}" class="btn btn-success">Edit</a>
                                                    <form action="{{ route('admin.siswa.delete', $item->id) }}" method="post">
                                                        @method("delete")
                                                        @csrf
                                                        <button class="btn btn-danger">Delete</button>
                                                    </form>
                                                </div>
                                            </td>
                                        </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <!--/ Basic table -->
    </div>
    @endsection

    @section('script')
    {{-- Jika anda mau menggunakan data tables sialahkan un command script ini --}}
    {{-- <script>
        $(function(){
            $.ajaxSetup({
                headers: {
                    'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                }
            });

            var table = $('#data-notif').DataTable({
                processing: true,
                serverSide: true,
                ajax: "url yang akan di tuju",
                columns: [
                {
                    data: null, "sortable": false,
                    render: function (data, type, row, meta) { return meta.row + meta.settings._iDisplayStart + 1; },
                },
                {
                    data: 'Column',
                    render: function (data, type, row, meta) {
                        return ``
                    },
                },
                {
                    data: 'id',
                    render: function (data, type, row, meta) {
                        return `
                            <div class="btn-group">
                                <button class="btn btn-flat-dark dropdown-toggle" type="button" id="dropdownMenuButton100" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    <img src="/app-assets/images/align-justify.svg">
                                </button>
                                <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                                    <a class="dropdown-item" href="/admin/eskul/edit/${row.id}">Edit</a>
                                    <a class="dropdown-item" href="javascript:void(0);" onclick="return hapus(${row.id})">Hapus</a>
                                </div>
                            </div>`
                    }
                },
                ],
                columnDefs: [
                {
                    className: 'control',
                    orderable: false,
                    targets: 0
                }
                ],
                dom:
                '<"d-flex justify-content-between align-items-center mx-0 row"<"col-sm-12 col-md-6"l><"col-sm-12 col-md-6"f>>t<"d-flex justify-content-between mx-0 row"<"col-sm-12 col-md-6"i><"col-sm-12 col-md-6"p>>',
                orderCellsTop: true,
                responsive: {
                    details: {
                        display: $.fn.dataTable.Responsive.display.modal({
                            header: function (row) {
                                var data = row.data();
                                return 'Details of ' + data['full_name'];
                            }
                        }),
                        type: 'column',
                        renderer: $.fn.dataTable.Responsive.renderer.tableAll({
                            tableClass: 'table'
                        })
                    }
                },
                language: {
                    paginate: {
                        // remove previous & next text from pagination
                        previous: '&nbsp;',
                        next: '&nbsp;'
                    }
                },
                drawCallback: () => {
                    $('.delete').click(function () {
                        const id = $(this).data(id)
                    })
                }
            });
        });

        function hapus(id){
            var table = $('#data-notif').DataTable();
            clearToastObj = toastr['error'](
                'Are You Delete?<br /><br /><button type="button" class="btn btn-danger btn-sm delete">Yes</button>',
                'Deleted',
                {
                    closeButton: true,
                    timeOut: 0,
                    extendedTimeOut: 0,
                    tapToDismiss: false,
                }
                );

            if (clearToastObj.find('.delete').length) {
                clearToastObj.delegate('.delete', 'click', function () {
                    toastr.clear(clearToastObj, { force: true });
                    clearToastObj = undefined;
                    $.ajax({
                        method: "GET",
                        url: "/admin/eskul/delete/" + id,
                        success: function (data) {
                            toastr['success']('Successfully Delete Data.', 'Successfully', {
                                closeButton: true,
                                tapToDismiss: false,
                                progressBar: true,
                            });
                            table.ajax.reload();
                        },
                        error: function (data) {
                            toastr['success']('👋 Chocolate oat cake jelly oat cake candy jelly beans pastry.', 'Progress Bar', {
                                closeButton: true,
                                tapToDismiss: false,
                                progressBar: true,
                                rtl: isRtl
                            });
                        }
                    });
                });
            }
        }
    </script>
    <script>
        $(function (){
            $('.hapus').on('click', function () {
                var id = $(this).attr('data-id');
                console.log(id);
            });
        });
    </script>
    <script>
        CKEDITOR.replace( 'editor1' );
    </script>
    @if(Session::get('create'))
        <script type="text/javascript">
            $(document).ready(function(){

                // Success Type
                toastr['success']('Successfully Create Data.', 'Successfully', {
                    closeButton: true,
                    tapToDismiss: false,
                    progressBar: true,
                });

            });
        </script>
    @endif

    @if(Session::get('update'))
        <script type="text/javascript">
            $(document).ready(function(){

                // Success Type
                toastr['success']('Successfully Update Data.', 'Successfully', {
                    closeButton: true,
                    tapToDismiss: false,
                    progressBar: true,
                });

            });
        </script>
    @endif --}}

@endsection