routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\JurusanController;
use App\Http\Controllers\SiswaController;
use App\Http\Controllers\ExampleController;
use App\Http\Controllers\KelasController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Auth::routes();

Route::get('/', [ExampleController::class , 'index']);
Route::group(['middleware' => 'auth', 'prefix' => 'admin' , 'as' => 'admin.'], function(){
    Route::get('/', [ExampleController::class, 'admin'])->name('admin');

    Route::get('/kelas', [KelasController::class, 'index'])->name('kelas');
    Route::get('/create', [KelasController::class, 'create'])->name('create');
    Route::post('/create', [KelasController::class, 'store'])->name('store');

    Route::get('/update/{kelas:id}', [KelasController::class, 'edit'])->name('edit');
    Route::put('/update/{id}', [KelasController::class, 'update'])->name('update');
    
    Route::delete('/delete/{id}', [KelasController::class, 'destroy'])->name('destroy');
    
    Route::group(['prefix' => 'siswa', 'as' => 'siswa.'], function(){
        Route::get('/', [SiswaController::class, 'index'])->name('index');
        Route::get('/create', [SiswaController::class, 'create'])->name('create');
        Route::post('/', [SiswaController::class, 'store'])->name('store');
        Route::get('/{siswa}', [SiswaController::class, 'edit'])->name('edit');
        Route::put('/{siswa}', [SiswaController::class, 'update'])->name('update');
        Route::delete('/{siswa}', [SiswaController::class, 'destroy'])->name('delete');
    });
    Route::group(['prefix' => 'jurusan', 'as' => 'jurusan.'], function(){
        Route::get('/', [JurusanController::class, 'jurusan'])->name('jurusan');
        Route::post('/simpanjurusan', [JurusanController::class, 'simpan'])->name('simpanJurusan');
        Route::post('/hapusjurusan/{id}', [JurusanController::class, 'hapus'])->name('hapusJurusan');
        Route::get('/editjurusan/{jurusan:id}', [JurusanController::class, 'edit'])->name('editJurusan');
        Route::get('/tambahjurusan', [JurusanController::class, 'tambah'])->name('tambahJurusan');
        Route::post('/ubahjurusan/{id}', [JurusanController::class, 'ubah'])->name('ubahJurusan');
    });

    Route::get('/kelas/create', [KelasController::class, 'create'])->name('create');
});

Route::get('/debug', [SiswaController::class, 'index']);

resources/views/layouts/app.blade.php
<!-- BEGIN: Body-->
@include('layouts.header')
<body class="vertical-layout vertical-menu-modern  navbar-floating footer-static  " data-open="click" data-menu="vertical-menu-modern" data-col="">

    <!-- BEGIN: Header-->
    @include('layouts.navbar')
    <!-- END: Header-->


    <!-- BEGIN: Main Menu-->
    @include('layouts.sidebar')
    <!-- END: Main Menu-->

    <!-- BEGIN: Content-->
    <div class="app-content content ">
        @yield('content')
    </div>
    <!-- END: Content-->

    <div class="sidenav-overlay"></div>
    <div class="drag-target"></div>

    <!-- BEGIN: Footer-->
    @include('layouts.footer')
    @yield('script')
</body>
<!-- END: Body-->

</html>

resources/views/layouts/footer.blade.php
<!-- BEGIN: Footer-->
<footer class="footer footer-static footer-light">
    <p class="clearfix mb-0"><span class="float-md-left d-block d-md-inline-block mt-25">COPYRIGHT &copy; 2021<a class="ml-25" href="https://www.sobat-teknologi.com" target="_blank">__</a>V.01.05.021</span></p>
</footer>
<button class="btn btn-primary btn-icon scroll-top" type="button"><i data-feather="arrow-up"></i></button>
<!-- END: Footer-->


<!-- BEGIN: Vendor JS-->
<script src="/app-assets/vendors/js/vendors.min.js"></script>
<!-- BEGIN Vendor JS-->

<!-- BEGIN: Page Vendor JS-->
<script src="/app-assets/vendors/js/extensions/toastr.min.js"></script>
<script src="/app-assets/vendors/js/editors/quill/katex.min.js"></script>
<script src="/app-assets/vendors/js/editors/quill/highlight.min.js"></script>
<script src="/app-assets/vendors/js/editors/quill/quill.min.js"></script>
<!-- END: Page Vendor JS-->

<!-- BEGIN: Theme JS-->
<script src="/app-assets/js/core/app-menu.js"></script>
<script src="/app-assets/js/core/app.js"></script>
<!-- END: Theme JS-->

<!-- BEGIN: Page JS-->
<script src="/app-assets/js/scripts/components/components-dropdowns.js"></script>
<script src="/app-assets/js/scripts/extensions/ext-component-toastr.js"></script>
<script src="/app-assets/js/scripts/forms/form-quill-editor.js"></script>
<script src="/app-assets/js/scripts/forms/form-file-uploader.js" defer></script>
<script src="/app-assets/vendors/js/tables/datatable/jquery.dataTables.min.js"></script>
<script src="/app-assets/vendors/js/tables/datatable/datatables.bootstrap4.min.js"></script>
<script src="/app-assets/vendors/js/tables/datatable/dataTables.responsive.min.js"></script>
<script src="/app-assets/vendors/js/tables/datatable/responsive.bootstrap4.js"></script>
<script src="/app-assets/vendors/js/tables/datatable/datatables.checkboxes.min.js"></script>
<script src="/app-assets/vendors/js/tables/datatable/datatables.buttons.min.js"></script>
<script src="/app-assets/vendors/js/tables/datatable/jszip.min.js"></script>
<script src="/app-assets/vendors/js/tables/datatable/pdfmake.min.js"></script>
<script src="/app-assets/vendors/js/tables/datatable/vfs_fonts.js"></script>
<script src="/app-assets/vendors/js/tables/datatable/buttons.html5.min.js"></script>
<script src="/app-assets/vendors/js/tables/datatable/buttons.print.min.js"></script>
<script src="/app-assets/vendors/js/forms/select/select2.full.min.js"></script>
<script src="/app-assets/js/scripts/forms/form-select2.js"></script>
<script src="/app-assets/js/scripts/forms/form-input-mask.js"></script>
<script src="/app-assets/vendors/js/forms/cleave/cleave.min.js"></script>
<script src="/app-assets/vendors/js/forms/cleave/addons/cleave-phone.us.js"></script>
<script src="https://cdn.ckeditor.com/ckeditor5/29.1.0/classic/ckeditor.js"></script>
<!-- END: Page JS-->

<script>
    $(window).on('load', function() {
        if (feather) {
            feather.replace({
                width: 14,
                height: 14
            });
        }
    })
</script>

<script type="text/javascript">
    var loadFile = function (event) {
        var output = document.getElementById('foto_profile_1');
        output.src = URL.createObjectURL(event.target.files[0]);
    };
    var loadFile2 = function (event) {
        var output = document.getElementById('foto_profile_2');
        output.src = URL.createObjectURL(event.target.files[0]);
    };
    var loadFile3 = function (event) {
        var output = document.getElementById('foto_profile3');
        output.src = URL.createObjectURL(event.target.files[0]);
    };
    var loadFile4 = function (event) {
        var output = document.getElementById('foto_profile4');
        output.src = URL.createObjectURL(event.target.files[0]);
    };
</script>

<script>
    function readURL(input) {
        if (input.files && input.files[0]) {

            var reader = new FileReader();

            reader.onload = function(e) {
                $('.image-upload-wrap').hide();

                $('.file-upload-image').attr('src', e.target.result);
                $('.file-upload-content').show();

                $('.image-title').html(input.files[0].name);
            };

            reader.readAsDataURL(input.files[0]);

        } else {
            removeUpload();
        }
    }

    function removeUpload() {
        $('.file-upload-input').replaceWith($('.file-upload-input').clone());
        $('.file-upload-content').hide();
        $('.image-upload-wrap').show();
    }

    $(function (){
        $('.image-upload-wrap').bind('dragover', function () {
            $('.image-upload-wrap').addClass('image-dropping');
        });

        $('.image-upload-wrap').bind('dragleave', function () {
            $('.image-upload-wrap').removeClass('image-dropping');
        });
    });
</script>

<script>
    ClassicEditor
        .create( document.querySelector( '#features' ) )
        .catch( error => {
            console.error( error );
        } );
</script>

{{-- <script>
    ClassicEditor
        .create( document.querySelector( '#description' ) )
        .catch( error => {
            console.error( error );
        } );
</script> --}}
<script>
    $(function(){
        $('form').on('submit', function(e){
            var btn = $(this).find('button[type=submit]'),
            loadingText = "<i class='fas fa-spinner fa-spin'></i> Loading...";
            btn.html(loadingText).addClass('disabled').attr('disabled', true);
        });
    })
</script>

resources/views/layouts/header.blade.php
<!DOCTYPE html>
<html class="loading" lang="en" data-textdirection="ltr">
<!-- BEGIN: Head-->

<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width,initial-scale=1.0,user-scalable=0,minimal-ui">
    <meta name="description" content="Vuexy admin is super flexible, powerful, clean &amp; modern responsive bootstrap 4 admin template with unlimited possibilities.">
    <meta name="keywords" content="admin template, Vuexy admin template, dashboard template, flat admin template, responsive admin template, web app">
    <meta name="author" content="PIXINVENT">
    <title>Dashboard </title>
    <link rel="apple-touch-icon" href="/app-assets/images/ico/apple-icon-120.png">
    <link rel="shortcut icon" href="/upload/img/favicon/">
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,300;0,400;0,500;0,600;1,400;1,500;1,600" rel="stylesheet">
    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous"/>


    <!-- BEGIN: Vendor CSS-->
    <link rel="stylesheet" type="text/css" href="/app-assets/vendors/css/vendors.min.css">
    <link rel="stylesheet" type="text/css" href="/app-assets/vendors/css/pickers/flatpickr/flatpickr.min.css">
    <link rel="stylesheet" type="text/css" href="/app-assets/vendors/css/extensions/toastr.min.css">
    <link rel="stylesheet" type="text/css" href="/app-assets/vendors/css/editors/quill/katex.min.css">
    <link rel="stylesheet" type="text/css" href="/app-assets/vendors/css/editors/quill/monokai-sublime.min.css">
    <link rel="stylesheet" type="text/css" href="/app-assets/vendors/css/editors/quill/quill.snow.css">
    <link rel="stylesheet" type="text/css" href="/app-assets/vendors/css/editors/quill/quill.bubble.css">
    <link rel="stylesheet" type="text/css" href="/app-assets/vendors/css/forms/select/select2.min.css">
    <!-- END: Vendor CSS-->
    <link rel="stylesheet" type="text/css" href="/app-assets/vendors/css/pickers/pickadate/pickadate.css">
    <!-- BEGIN: Theme CSS-->
    <link rel="stylesheet" type="text/css" href="/app-assets/vendors/css/vendors.min.css">
    <link rel="stylesheet" type="text/css" href="/app-assets/vendors/css/tables/datatable/dataTables.bootstrap4.min.css">
    <link rel="stylesheet" type="text/css" href="/app-assets/vendors/css/tables/datatable/responsive.bootstrap4.min.css">
    <link rel="stylesheet" type="text/css" href="/app-assets/vendors/css/tables/datatable/buttons.bootstrap4.min.css">
    <link rel="stylesheet" type="text/css" href="/app-assets/vendors/css/tables/datatable/rowGroup.bootstrap4.min.css">
    <link rel="stylesheet" type="text/css" href="/app-assets/vendors/css/pickers/flatpickr/flatpickr.min.css">    

    <link rel="stylesheet" type="text/css" href="/app-assets/css/plugins/forms/form-file-uploader.css">

    <link rel="stylesheet" type="text/css" href="/app-assets/css/bootstrap.css">
    <link rel="stylesheet" type="text/css" href="/app-assets/css/bootstrap-extended.css">
    <link rel="stylesheet" type="text/css" href="/app-assets/css/colors.css">
    <link rel="stylesheet" type="text/css" href="/app-assets/css/components.css">
    <link rel="stylesheet" type="text/css" href="/app-assets/css/themes/dark-layout.css">
    <link rel="stylesheet" type="text/css" href="/app-assets/css/themes/bordered-layout.css">
    <link rel="stylesheet" type="text/css" href="/app-assets/css/themes/semi-dark-layout.css">

    <!-- BEGIN: Page CSS-->
    <link rel="stylesheet" type="text/css" href="/app-assets/css/core/menu/menu-types/vertical-menu.css">
    <link rel="stylesheet" type="text/css" href="/app-assets/css/plugins/forms/pickers/form-flat-pickr.css">
    <link rel="stylesheet" type="text/css" href="/app-assets/css/plugins/extensions/ext-component-toastr.css">
    <link rel="stylesheet" type="text/css" href="/app-assets/css/plugins/forms/form-quill-editor.css">
    <link rel="stylesheet" href="/app-assets/css/uploader.css">
    <link rel="stylesheet" href="/app-assets/css/uploader-2.css">
    <link rel="stylesheet" href="/app-assets/css/uploader-3.css">
    <link rel="stylesheet" type="text/css" href="/app-assets/css/plugins/forms/pickers/form-flat-pickr.css">
    <link rel="stylesheet" type="text/css" href="/app-assets/css/plugins/forms/pickers/form-pickadate.css">
    <!-- END: Page CSS-->

    <!-- BEGIN: Custom CSS-->
    <link rel="stylesheet" type="text/css" href="/assets/css/style.css">
    <script src="https://cdn.ckeditor.com/4.16.1/standard/ckeditor.js"></script>

</head>
<!-- END: Head-->

resources/views/layouts/navbar.blade.php
<!-- BEGIN: Header-->
<nav class="header-navbar navbar navbar-expand-lg align-items-center floating-nav navbar-light navbar-shadow">
    <div class="navbar-container d-flex content">
        <div class="bookmark-wrapper d-flex align-items-center">

        </div>
        <ul class="nav navbar-nav align-items-center ml-auto">

            <li class="nav-item dropdown dropdown-user"><a class="nav-link dropdown-toggle dropdown-user-link" id="dropdown-user" href="javascript:void(0);" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <div class="user-nav d-sm-flex d-none"><span class="user-name font-weight-bolder">{{ Auth::user()->name }}</span><span class="user-status">{{ Auth::user()->email }}</span></div><span class="avatar"><img class="round" src="/avatar.png" alt="avatar" height="40" width="40"><span class="avatar-status-online"></span></span>
            </a>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdown-user">
                {{-- <a class="dropdown-item" href="#"><i class="mr-50" data-feather="user"></i> Profile</a> --}}
                <div class="dropdown-divider"></div>
                <a class="dropdown-item"  onclick="event.preventDefault();document.getElementById('logout-form').submit();"><i class="mr-50" data-feather="power"></i> Logout</a>
                <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                    @csrf
                </form>
            </div>
        </li>
    </ul>
</div>
</nav>

resources/views/layouts/sidebar.blade.php
<div class="main-menu menu-fixed menu-light menu-accordion menu-shadow" data-scroll-to-active="true">
    <div class="navbar-header">
        <ul class="nav navbar-nav flex-row">
            <li class="nav-item mr-auto"><a class="navbar-brand" href="{{ url('/') }}">
                <span class="brand-logo">
                    <img src="/logo.svg" style="max-width: 147px !important; margin-left: 22px;margin-bottom: 20px !important;">
                </span>
                {{-- <h2 class="brand-text">Shirvano</h2> --}}
            </a></li>
        </ul>
    </div>
    <div class="shadow-bottom"></div>
    <div class="main-menu-content">
        <ul class="navigation navigation-main" id="main-menu-navigation" data-menu="menu-navigation">
            <li class=" navigation-header"><span data-i18n="Apps &amp; Pages">  Name Application</span><i data-feather="more-horizontal"></i>
            </li>

            <li class="nav-item {{ Route::is("admin.admin") ? "active" : "" }}">
                <a class="d-flex align-items-center" href="{{ route('admin.admin') }}">
                    <i data-feather='cast'></i>
                    <span class="menu-title text-truncate" data-i18n="Dashboard">Home</span>
                </a>
            </li>

            <li class="nav-item {{ Route::is(['admin.siswa.index', 'admin.siswa.create', 'admin.siswa.edit']) ? "active" : "" }}">
                <a class="d-flex align-items-center" href="{{ route('admin.siswa.index') }}">
                    <i data-feather='cast'></i>
                    <span class="menu-title text-truncate" data-i18n="Dashboard">Siswa</span>
                </a>
            </li>
            <li>
                <a class="d-flex align-items-center" href="{{ route('admin.jurusan.jurusan') }}">
                    <i data-feather='cast'></i>
                    <span class="menu-title text-truncate" data-i18n="Dashboard">Jurusan</span>
                </a>
                </li>
            <li class="nav-item {{ Route::is(['admin.kelas', 'admin.edit']) ? "active" : "" }}">
                <a class="d-flex align-items-center" href="{{ route('admin.kelas') }}">
                    <i data-feather='cast'></i>
                    <span class="menu-title text-truncate" data-i18n="Dashboard">Kelas</span>
                </a>
            </li>

            <li class=" nav-item"><a class="d-flex align-items-center" href="#"><i data-feather='home'></i><span class="menu-title text-truncate" data-i18n="Invoice">Menu</span></a>
                <ul class="menu-content">
                    <li class="">
                        <a class="d-flex align-items-center" href="">
                            <i data-feather='image'></i>
                            <span class="menu-title text-truncate" data-i18n="Dashboard">Sub Menu</span>
                        </a>
                    </li>
                </ul>
            </li>
        </ul>
    </div>
</div>
<!-- END: Main Menu -->